# Paths
LOGS_PATH: Example/log/path # You can add any path you want
BACKUP_PATH: Example/backup/path # You can add any path you want
INVENTORY_FILE: Example/path/to/inventory.csv # You can load inventory from wherever you want